### ISSUE TITLE
Crash when changing mode 

### ISSUE THREAD

**Issue by jeyremy** [nitaybz/homebridge-tado-ac#101]
Hi, 

i get a new error when i set ac off or on since today on last version, here the output : 

2020-11-10 18:28:35] [Tado AC] Étage AC  -> Setting New State:
[2020-11-10 18:28:35] [Tado AC] {
  "termination": {
    "type": "TIMER"
  },
  "setting": {
    "type": "AIR_CONDITIONING",
    "power": "OFF"
  }
}
[2020-11-10 18:28:35] [Tado AC] ERROR: Request failed with status code 422
[2020-11-10 18:28:35] [Tado AC] ERROR setting active to false
[2020-11-10 18:28:36] TypeError: platform.refreshState is not a function
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-tado-ac/tado/StateHandler.js:82:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

**Comment by nitaybz** [comment]
try the latest release v4.0.13
it should fix it

**Comment by jeyremy** [comment]
Hi ! Thanks a lot, it does not crash anymore but I still can’t turn off my tado AC

Thanks a lot for your reply

**Comment by nitaybz** [comment]
There is another error there... 422... I think it's related to authorization... please add debug logs and show me when homebridge restarts.... also verify your username and password are correct

**Comment by jeyremy** [comment]
Hi again, 
sorry for my long delay... with debug mode : startup is normal but, when  changing mode i got this : 
`[2020-11-22 8:18:52] [Tado AC] [{"name":"Jeremy Luisetti","email":"xxxx","username":"xxxx","id":"xxxx","homes":[{"id":133443,"name":"Maison Salernes"}],"locale":"fr_FR","mobileDevices":[{"name":"iPhone Jérémy 2","id":1050471,"settings":{"geoTrackingEnabled":true,"onDemandLogRetrievalEnabled":true,"pushNotifications":{"lowBatteryReminder":true,"awayModeReminder":true,"homeModeReminder":true,"openWindowReminder":true,"energySavingsReportReminder":true,"incidentDetection":true}},"location":{"stale":false,"atHome":true,"bearingFromHome":{"degrees":0,"radians":0},"relativeDistanceFromHomeFence":0},"deviceMetadata":{"platform":"iOS","osVersion":"14.2","model":"iPhone11,2","locale":"fr"}},{"name":"iPad De Jeremy","id":1255218,"settings":{"geoTrackingEnabled":false,"pushNotifications":{"lowBatteryReminder":true,"awayModeReminder":true,"homeModeReminder":true,"openWindowReminder":true,"energySavingsReportReminder":true,"incidentDetection":true}},"deviceMetadata":{"platform":"iOS","osVersion":"14.0","model":"iPad7,11","locale":"fr"}}]},{"name":"Laura Tursi","email":"xxxx","username":"xxxx","id":"xxxx","homes":[{"id":133443,"name":"Maison Salernes"}],"locale":"fr_FR","mobileDevices":[{"name":"iPad De Laura","id":435067,"settings":{"geoTrackingEnabled":false},"deviceMetadata":{"platform":"iOS","osVersion":"12.0.1","model":"iPad5,3","locale":"fr"}},{"name":"iPhone De Laura","id":434523,"settings":{"geoTrackingEnabled":true,"pushNotifications":{"lowBatteryReminder":true,"awayModeReminder":true,"homeModeReminder":true,"openWindowReminder":true,"energySavingsReportReminder":true,"incidentDetection":true}},"location":{"stale":false,"atHome":true,"bearingFromHome":{"degrees":97.83782564687088,"radians":1.7075921905300477},"relativeDistanceFromHomeFence":0},"deviceMetadata":{"platform":"iOS","osVersion":"13.6","model":"iPhone11,2","locale":"fr"}}]}]
[2020-11-22 8:18:52] [Tado AC] >>> Got Users from tado° API
[2020-11-22 8:18:52] [Tado AC] Token successfully acquired from tado° API
[2020-11-22 8:18:52] [Tado AC] Creating PUT request to tado° API --->
[2020-11-22 8:18:52] [Tado AC] https://my.tado.com/api/v2/homes/133443/zones/2/overlay
[2020-11-22 8:18:52] [Tado AC] data: {"termination":{"type":"TIMER"},"setting":{"type":"AIR_CONDITIONING","power":"OFF"}}
[2020-11-22 8:18:53] [Tado AC] ERROR: Request failed with status code 422
[2020-11-22 8:18:53] [Tado AC] {
  errors: [
    {
      code: 'durationInSecondsMandatoryForTimer',
      title: 'Property [termination.durationInSeconds] of class [class com.tado.publicapi.OverlayTerminationConditionCommand] with value [null] does not pass custom validation'
    }
  ]
}
[2020-11-22 8:18:53] [Tado AC] ERROR setting active to false
[2020-11-22 8:18:56] [Tado AC] Got Temperature Unit from Storage  >>> CELSIUS <<<
[2020-11-22 8:18:56] [Tado AC] Getting Zone`

**Comment by nitaybz** [comment]
please check the latest

**Comment by jeyremy** [comment]
Thanks a lot, it's working properly now
