### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rafacampoamor** [nitaybz/homebridge-tado-ac#9]
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN my.tado.com:443
    at Object._errnoException (util.js:1024:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
```

**Comment by nitaybz** [comment]
this error usually happens when homebridge can't reach tado api.
it can happen because of no internet or their servers are down...

can you confirm that this issue is not happening all the time?
I'll try to work on a fix that will prevent homebridge from crushing.

**Comment by rafacampoamor** [comment]
I’ll watch it and report it back. It’s the first time with this version since installing it yesterday. If I don’t mislead, I remember this happening in the old version as well. Can be?

**Comment by nitaybz** [comment]
yes it did happen before... I'll try to work on a solution

**Comment by nitaybz** [comment]
check out my last version v2.2
should solve the issue

**Comment by nitaybz** [comment]
issue is solved for now so i'm closing the ticket

**Comment by roe1974** [comment]
i think issue is back with 2..3.1 :-(

see @ https://github.com/nitaybz/homebridge-tado-ac/issues/29

Richard

**Comment by rafacampoamor** [comment]
Just got this error again on V3

**Comment by nitaybz** [comment]
did it crash homebridge?

**Comment by rafacampoamor** [comment]
Yes. Just got home and saw Homebridge was down because of this

[2019-1-28 12:13:11] [Tado AC] Rafael P. Campoamor is Out!
events.js:167
      throw er; // Unhandled 'error’ event
     ^

Error: getaddrinfo EAI_AGAIN my.tado.com my.tado.com:443 <http://my.tado.com:443/>
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

**Comment by nitaybz** [comment]
any other logs? I don't see any reference to the code so I'm not sure where it come from

**Comment by nitaybz** [comment]
also I'm pretty sure I covered all tado API calls. are you positive it's coming from the latest version?

**Comment by roe1974** [comment]
no problem here...everything works fine.....

**Comment by rafacampoamor** [comment]
pi@CampoaPi:~ $ tail -f /var/log/homebridge.err
      ^

Just this:

Error: getaddrinfo EAI_AGAIN my.tado.com my.tado.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
Emitted 'error' event at:
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

**Comment by rafacampoamor** [comment]
Just reinstalled Todo-AC plugin yesterday but… How do I make sure I have the latest version?

**Comment by rafacampoamor** [comment]
pi@CampoaPi:~ $ npm homebridge-tado-ac -v
5.6.0

**Comment by nitaybz** [comment]
this is not the version...
please run:
npm list -g homebridge-tado-ac

**Comment by rafacampoamor** [comment]
This is weird…

pi@CampoaPi:~ $ npm list -g homebridge-tado-ac
npm WARN npm npm does not support Node.js v11.0.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
/usr/local/lib
└── (empty)

**Comment by nitaybz** [comment]
run 
node -v

**Comment by rafacampoamor** [comment]
pi@CampoaPi:~ $ node -v
v11.0.0

**Comment by nitaybz** [comment]
as it looks, your npm is not supporting that new version... try upgrading npm or downgrading node

also you need to take into considerations that installing new node version should also include installing new homebridge on top of that so it can sync with he new version
